name: gedung_tertinggi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/images/burj/
    - assets/images/shanghai/
    - assets/images/mecca/
    - assets/images/ping/
    - assets/images/lotte/
    - assets/images/one/
    - assets/images/Frame 1.png
  uses-material-design: true
